//
//  NSError+AWSDKError.h
//  AWSDK
//
//  Created by Steven Uy on 1/13/17.
//  Copyright © 2018 American Well.
//  All rights reserved.
//
//  It is illegal to use, reproduce or distribute
//  any part of this Intellectual Property without
//  prior written authorization from American Well.
//

#import <Foundation/Foundation.h>

#pragma mark - AWSDKErrorDomain Constants
/**
 AWSDKErrorDomain Constants
 */

/**
 Error domain to cover errors generated by the SDK, including calls to the American Well Telehealth Platform server

 @since 3.0.0
 */
extern _Nonnull NSErrorDomain const AWSDKErrorDomainSDK;

/**
 Error domain to cover errors generated by a network failue.

 @since 3.0.0
 */
extern _Nonnull NSErrorDomain const AWSDKErrorDomainNetwork;

/**
 Error domain to cover unknown errors

 @since 3.0.0
 */
extern _Nonnull NSErrorDomain const AWSDKErrorDomainUnknown;

/**
 Category for NSError exposing convience methods to access AWSDK specific items in the error's user info dictionary.

 @since 3.0.0
 */
@interface NSError (AWSDKErrors)

@property (readonly, nonatomic, nullable) NSDictionary *validationErrors;

@end
