//
//  AWSDKCost.h
//  AWSDK
//
//  Created by Calvin Chestnut on 10/28/15.
//  Copyright © 2015 American Well.
//  All rights reserved.
//
//  It is illegal to use, reproduce or distribute
//  any part of this Intellectual Property without
//  prior written authorization from American Well.
//

#import <AWSDK/AWSDKDataObject.h>

/**
 The cost or estimated cost of a visit.

 @since 1.0.0
 */
@protocol AWSDKCost <AWSDKDataObject>

/**
 @name Read-Only Properties
 */

/**

 An enumeration describing the status of the insurance eligibility request.

 @since 4.3.0
 */

typedef NS_ENUM(NSInteger, AWSDKInsuranceEligibilityStatus) {

    /**
     The consumer is not covered or not on file at the time of the eligibility request.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusNotCovered,

    /**
     The consumer has active coverage at the time of the eligibility request.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusCovered,

    /**
     The eligibility request failed.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusFailed,

    /**
     The eligibility request was cancelled before completion.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusCancelled,

    /**
     The remote server that the American Well Telehealth Platform contacted to establish eligibility required validation information.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusRequestValidationResponse,

    /**
     No status was returned.

     @since 4.3.0
    */
    AWSDKInsuranceEligibilityStatusEmpty
};

#pragma mark - Read-Only Properties
/**
 float representing original, base cost of the visit.

 @since 1.0.0
 */
@property (nonatomic, readonly) float baseCost;

/**
 float representing extension cost of any extensions accepted by the consumer during the visit.

 @since 1.0.0
 */
@property (nonatomic, readonly) float extensionCost;

/**
 float representing the amount that the consumer will actually pay, total of the base and extension cost.

 @since 1.0.0
 */
@property (nonatomic, readonly) float expectedCopay;

/**
 Boolean value indicating if the provider has waived the cost of the visit.

 @since 1.0.0
 */
@property (nonatomic, readonly) BOOL totalCostWaived;

/**
 NSString representing the supplied coupon code for the visit, otherwise _nil_ if none was provided.

 @since 1.0.0
 */
@property (nonatomic, nullable, readonly) NSString *couponCode;

/**
 NSString proposed coupon code suggested by the provider before the visit, otherwise _nil_ if none was provided.

 @since 1.0.0
 */
@property (nonatomic, nullable, readonly) NSString *proposedCouponCode;

/**
 Boolean value indicating if a coupon code can be applied to a visit.

 @since 3.0.0
 */
@property (nonatomic, readonly) BOOL canApplyCouponCode;

#pragma mark - Read-Only Properties

/**
 BOOL set _TRUE_ if the cost object represents the billing will be deferred to a later date. The consumer will receive a secure message when they are billed.

 @since 3.0.0
 */
@property (nonatomic, assign, readonly) BOOL isBillingDeferred;

/**
 NSString representing a configurable displayable message in the practice configuration to alert consumers about deferred billing.

 @since 3.0.0
 */
@property (nonatomic, nullable, readonly) NSString *deferredBillingText;

/**
 NSString representing a configurable displayable message in the practice configuration to alert consumers during wrap up that their billing has been deferred.

 @since 3.0.0
 */
@property (nonatomic, nullable, readonly) NSString *deferredBillingWrapUpText;

/**
 Boolean value indicating if the cost has changed when being transferred from one provider to another.

 @since 2.1.2
 */
@property (nonatomic, readonly) BOOL hasCostChangedWithVisitTransfer;

/**
 Message to be shown regarding payment information

 @since 3.2.0
 */
@property (nonatomic, nullable, readonly) NSString *paymentMessage;

/**
 The AWSDKInsuranceEligibilityStatus status of the insurance eligibility request

 @since 4.3.0
 */
@property (nonatomic, readonly) AWSDKInsuranceEligibilityStatus eligibilityRequestStatus;

/**
 The eligibilityExceptionReason describes why the eligibility request failed.

 @since 4.3.0
 */
@property (nonatomic, nullable, readonly) NSString *eligibilityExceptionReason;

/**
 Generated by the SDK when there was an insurance eligibility exception.

 @since 4.3.0
 */
@property (nonatomic, nullable, readonly) NSError *eligibilityRequestError;

#pragma mark - Convenience Methods
/**
 @name Convenience Methods
 */

/**
 Boolean value indicating if the visit has a cost attached.

 @return Bool value indicating if the visit is free.

 @since 1.0.0
 */
- (BOOL)isFree;

@end
